[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"  # this is really crap as we have a moving target here
  name = "github.com/streadway/amqp"
