[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  revision = "e5adc2ada8b8efff032bf61173a233d143e9318e"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/jhunt/vcaptive"
